### ISSUE TITLE
dont work in ubuntu 16.4

### ISSUE THREAD

**Issue by abbasnaqdi** [appdictive/ADBRemoteConnect#1]
Hi.
This plugin is dont work in android studio 2.3.3.0 in ubuntu 16.4 LTS but is worked in windows 10 . 
please fix this problem thanks .

**Comment by JesperLR** [comment]
Hi Abbas
Thanks for your interest in the plugin! 
I am aware of the issue, it should be fixed in version 1.5 - for some reason it is still awaiting approval at Jetbrains plugin system, but should be out real soon though :) Please let me know if the 1.5 version does not fix it for you.

**Comment by JesperLR** [comment]
Fixed in version 1.5 - is approved and out now.
