### ISSUE TITLE
This plugin is not running on Android Studio 2.3.3

### ISSUE THREAD

**Issue by abbasnaqdi** [appdictive/ADBRemoteConnect#2]
Hello .

Version 1.5 This plugin is not running on Android Studio 2.3.3.
I use the Ubuntu 16.4 operating system and this plugin was already running for me, but now it's not running and it's a problem.

When I want to run this plugin manually, I encounter the following error:

> Error: Could not find or load main class ADBWiFiConnectGUI.jar

**Comment by wyl530274554** [comment]
win 8.1 android studio 2.3.3 
Nothing heppen when I click the wifi-conn  icon.

**Comment by JesperLR** [comment]
Have you tried the newest version 1.6 - is that working for you?

**Comment by JesperLR** [comment]
Version 1.7 has been released and should fix this issue.
