### ISSUE TITLE
unable to attach debugger

### ISSUE THREAD

**Issue by phileo** [appdictive/ADBRemoteConnect#4]
when ADBWiFiConnect is running, I am unable to attach the debugger.

**Comment by JesperLR** [comment]
Is this consistent behavior for you? You are able to attach debugger before starting ADBWiFiConnect and unable to after? Does it matter if ADBWiFiConnect is in foreground or minimized?

**Comment by phileo** [comment]
Steps to reproduce (Android Studio 2.3.3):
1) Run ADBWiFiConnect, selected desired device from list of saved devices
2) Run and load app
3) Select attach debugger and select process
4) Press stop
5) Select attach debugger again

Observe there is no process to attach

**Comment by JesperLR** [comment]
Can you please provide a bit more detailed info on the steps - e.g. do you get a WiFi connection to your device? Do you keep the USB connection? 
What is "stop"? If it's the red square button in Android Studio then you are stopping the process - which would be why you can't attach the debugger to it after having stopped it. But this has nothing to do with  ADBWiFiConnect :)

**Comment by phileo** [comment]
it's fairly random.  I am not able to reproduce the issue all the time.  It's similar to how sometimes I cannot connect to my saved devices, even though I know the IP address hasn't changed.  If you wish, you can close this for now, since the workaround appears to be delete, disconnect and then reconnect
