### ISSUE TITLE
Not working with Android Studio 3.0

### ISSUE THREAD

**Issue by spyzip** [appdictive/ADBRemoteConnect#7]
I installed the plugin but when clicking on the plugin icon nothing happens

**Comment by hadilo** [comment]
work well on my mac AS 3.0 stable + lollipop

**Comment by AlexVPerl** [comment]
@hadilo I'm running Mac AS 3.0 as well. I just installed the plug-in. 

I cant seem to find how to open the window anywhere in the menus. 

How do I access it, what do I do?

Thanks!

**Comment by AlexVPerl** [comment]
Ok, NVM. I just noticed an extra button in the menu. Was able to connect without issues :)

**Comment by spyzip** [comment]
So the problem is with my AS?

**Comment by JesperLR** [comment]
Please see https://github.com/appdictive/ADBWiFiConnect/issues/5

**Comment by spyzip** [comment]
ok, thanks
